apiVersion: v2
appVersion: 2.0.0
name: vsphere-csi
description: DEPRECATED - See https://vsphere-tmm.github.io/helm-charts/
version: 0.0.3
keywords:
  - vsphere
  - vmware
  - csi
home: https://github.com/kubernetes-sigs/vsphere-csi-driver
icon: https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/docs/images/vmware_logo.png
sources:
  - https://github.com/kubernetes-sigs/vsphere-csi-driver
maintainers:
  - name: chogan
    email: chogan@vmware.com
  - name: Myles Gray
    email: mylesg@vmware.com
dependencies: # A list of the chart requirements (optional)
  - name: vsphere-cpi
    version: 0.1.3
    repository: https://kubernetes-charts.storage.googleapis.com
    enabled: true