{{- if .Values.config.enabled | default .Values.global.config.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.name }}
  labels:
    {{- include "vsphere-csi.labels" . | nindent 4 }}
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = "{{ .Values.config.clusterId }}"
    [VirtualCenter "{{ .Values.config.vcenter | default .Values.global.config.vcenter }}"]
    user = "{{ .Values.config.username | default .Values.global.config.username }}"
    password = "{{ .Values.config.password | default .Values.global.config.password }}"
    port = "443"
    insecure-flag = "1"
    ca-file = "{{ .Values.config.cafile }}"
    datacenters = "{{ .Values.config.datacenter | default .Values.global.config.datacenter }}"
    {{ if .Values.netconfig.enabled }}
    targetvSANFileShareDatastoreURLs = "{{ .Values.netconfig.datastore }}"
    {{ end }}
    {{ if .Values.netconfig.enabled }}
    [NetPermissions "A"]

    ips = "{{ .Values.netconfig.ips }}"
    permissions = "{{ .Values.netconfig.permissions }}"
    rootsquash = "{{ .Values.netconfig.rootsquash }}"
    {{ end }}
{{- end -}}
